### ISSUE TITLE
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied

### ISSUE THREAD

**Issue by cgerstle-droid** [cobbzilla/s3s3mirror#109]
After years of not having any problems with s3s3mirror, I believe that a change in permissions within my organization results now in:

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 49C4889A16C25AD7), S3 Extended Request ID: Dz1/nf2/ehWbrcz0L2zw1ijyBmdjo+1JWJvpyDBIIh7JAYWVUWyXvxDjBOjPQz1UBpM4mJ881KQ=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1530)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1168)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:949)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:662)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:636)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:619)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:587)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:574)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:446)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4044)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3981)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:777)
        at org.cobbzilla.s3s3mirror.KeyLister.s3getFirstBatch(KeyLister.java:96)
        ... 3 more
main INFO : org.cobbzilla.s3s3mirror.MirrorMaster - mirror: completed
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - stopping CopyMaster...
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - CopyMaster stopped
Thread-1 INFO : org.cobbzilla.s3s3mirror.MirrorStats -

The folks who locked down our s3 buckets don't understand what has happened in that it appears that the code (KeyLister.java) is simply trying to LIST objects - which we believe are all world-read. And this behavior is not consistent. One of our buckets does not have this issue, another does. Can you provide details as to exactly what KeyLister.java is attempting that would cause a 403 for one bucket but not another? Happy to "talk" by email or phone if that is easier/faster.

**Comment by cobbzilla** [comment]
The only S3 API calls that `KeyLister` makes are `listObjects` and `listNextBatchOfObjects`. 

It is possible for a bucket to be world-readable but not world-listable. s3s3mirror requires "list" permissions on the read-bucket side.
