### ISSUE TITLE
Unexpectedly returns exit status 0 on error

### ISSUE THREAD

**Issue by egeland** [cobbzilla/s3s3mirror#51]
First, thanks for creating this tool, it's very useful!

I'm using `s3s3mirror-2.0.2-SNAPSHOT.jar` from the `2.0-stable` branch.

Java info:

```
$ java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

If I just run the included `s3s3mirror.sh` script, giving no arguments, the exit code (after displaying the usage info) is `1`, which is fair enough.

However, if I try to use the tool with a deliberately wrong set of AWS keys, the exit code (confusingly) is `0`.

The same happens if I just use the jar directly:

```
$ java -jar s3s3mirror-2.0.2-SNAPSHOT.jar --max-connections 500 --max-threads 500 --endpoint s3.amazonaws.com redacted-source redacted-target
main INFO : org.cobbzilla.s3s3mirror.MirrorMaster - version null starting
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #0): com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Stat
us Code: 403; Error Code: InvalidAccessKeyId; Request ID: 2C95D899071B81BF), S3 Extended Request ID: RYh8tAhvU9TYbeKITTtbCV9Ljl0kNyN8W7yhQCbgHH4vYoxYhDE6KuSDCC4wj+dQ1ck5i6dz53A=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #1): com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Stat
us Code: 403; Error Code: InvalidAccessKeyId; Request ID: 2B74075641A9B698), S3 Extended Request ID: 0TLLVEAYuMWESQOPAB5aXINpBRvhGe86YJ1QsLDrIT5MhNa3c2qPGgc6lIkA9WweCfQ2DG7RtNQ=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #2): com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: C171D99635380E2D), S3 Extended Request ID: FE0HteSnYfuiQz7J83lzyx32O0Yl8yJxCy/3c1L0BACVYlfOPSbYHJhcH+QwkISWrUIhMZS1IzQ=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #3): com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: B185D23FF91A09F4), S3 Extended Request ID: PYvIU1mf/P0BcrmyZxqZFKKaZ0ZbybooUhsSDsczT3/RiUwau5KbIBBoqwy4k/WyN37F/xceGy8=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #4): com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8C81A8830D6D9DAD), S3 Extended Request ID: ef8SJMsejbKYd9DA+v6VBU8tpyo6zU8IkXsjaNWLX52hCUyE5irRAe81nXfNnMME1zdnoXXWxV4=
Thread-2 ERROR: org.cobbzilla.s3s3mirror.KeyMaster - Unexpected exception in MirrorMaster (org.cobbzilla.s3s3mirror.store.s3.master.S3CopyMaster): java.lang.IllegalStateException: getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8C81A8830D6D9DAD), S3 Extended Request ID: ef8SJMsejbKYd9DA+v6VBU8tpyo6zU8IkXsjaNWLX52hCUyE5irRAe81nXfNnMME1zdnoXXWxV4=
java.lang.IllegalStateException: getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8C81A8830D6D9DAD), S3 Extended Request ID: ef8SJMsejbKYd9DA+v6VBU8tpyo6zU8IkXsjaNWLX52hCUyE5irRAe81nXfNnMME1zdnoXXWxV4=
        at org.cobbzilla.s3s3mirror.KeyLister.getFirstBatch(KeyLister.java:107)
        at org.cobbzilla.s3s3mirror.KeyLister.<init>(KeyLister.java:36)
        at org.cobbzilla.s3s3mirror.KeyMaster.run(KeyMaster.java:80)
        at java.lang.Thread.run(Thread.java:701)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8C81A8830D6D9DAD), S3 Extended Request ID: ef8SJMsejbKYd9DA+v6VBU8tpyo6zU8IkXsjaNWLX52hCUyE5irRAe81nXfNnMME1zdnoXXWxV4=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1020)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:675)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:429)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:291)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3655)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3607)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:623)
        at org.cobbzilla.s3s3mirror.store.s3.S3FileStore.listObjects(S3FileStore.java:32)
        at org.cobbzilla.s3s3mirror.KeyLister.getFirstBatch(KeyLister.java:94)
        ... 3 more
main INFO : org.cobbzilla.s3s3mirror.MirrorMaster - mirror: completed
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - stopping S3CopyMaster...
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - S3CopyMaster stopped
Thread-1 INFO : org.cobbzilla.s3s3mirror.MirrorStats - 
--------------------------------------------------------------------
STATS BEGIN
read: 0
copied: 0
copy errors: 0
uploaded: 0
upload errors: 0
deleted: 0
delete errors: 0
duration: 0:00:06
read rate: 0.0/minute
copy+upload rate: 0.0/minute
delete rate: 0.0/minute
bytes copied: 0 bytes
bytes copied: 0 bytes
GET operations: 5
COPY operations: 0
PUT operations: 0
DELETE operations: 0
STATS END
--------------------------------------------------------------------
$ echo $?
0
```

Would you mind making it exit with `1` when errors are encountered, please? (Or at least non-`0`?)
Otherwise scripting becomes very hard..

**Comment by cobbzilla** [comment]
Yes, it would be better to exit with a non-zero status if we cannot even connect to S3. Marking this as a bug. The fix is not hard, if someone beats me to the punch I would be happy.
