### ISSUE TITLE
AWS Signature Version 4 algorithm authentication problem

### ISSUE THREAD

**Issue by Observer99** [cobbzilla/s3s3mirror#71]
s3s3mirror failed to access S3 bucket in Frankfurt.

From AWS site: "In the China (Beijing), EU (Frankfurt) and Asia Pacific (Seoul) regions, Amazon S3 supports only Signature Version 4. In all other regions, Amazon S3 supports both Signature Version 4 and Signature Version 2." 

More information about this issue can be found here:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

The error message:

main INFO : org.cobbzilla.s3s3mirror.MirrorMaster - version 1.2.5 starting
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #0): com.amazonaws.services.s3.model.AmazonS3Exception: **The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256**. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 3072471487FBF916), S3 Extended Request ID: bM0ur9Ibfl7oTCKolt3h/KBe9DDB/mzCa6rZ8Cah+hYCZC+bPBuNiN+Qoaic/vhOlch6vdK6URg=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #1): com.amazonaws.services.s3.model.AmazonS3Exception: **The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256**. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 8E8145B795F73407), S3 Extended Request ID: gpyKykynb71nD7KgknPff9W6WR/9tit7xAf2sMecjtsF4wd9kQLpdhsnJz+kL1shqO+X09sLF3Y=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #2): com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: C5FD86C5E5EDE39C), S3 Extended Request ID: owvOKhepn4l4YWB23xP7fnwgTwkNQOOzX6mE21mvQCJMwsgWZy/uTLtX75KLrRpILLQ44ohsMKY=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #3): com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 2AAD2A3775A0D7E6), S3 Extended Request ID: 2NDIp2Z5EWynnH82wqCxtCdQpvK+GGbMFMQ8B0wu9kljvlMGS8OojumsuCQUjnJlOhApcoAksDE=
Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #4): com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: F9686BB975A72741), S3 Extended Request ID: 80xvNi3MB7XTU7BpjDY7AZ+OY9eJXasWakIS35tnlevhFct6D9m8tLFtLsjmzbY0+GzqsMZMkfQ=
Thread-2 ERROR: org.cobbzilla.s3s3mirror.KeyMaster - Unexpected exception in MirrorMaster: java.lang.IllegalStateException: s3getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: F9686BB975A72741), S3 Extended Request ID: 80xvNi3MB7XTU7BpjDY7AZ+OY9eJXasWakIS35tnlevhFct6D9m8tLFtLsjmzbY0+GzqsMZMkfQ=
java.lang.IllegalStateException: s3getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: F9686BB975A72741), S3 Extended Request ID: 80xvNi3MB7XTU7BpjDY7AZ+OY9eJXasWakIS35tnlevhFct6D9m8tLFtLsjmzbY0+GzqsMZMkfQ=
        at org.cobbzilla.s3s3mirror.KeyLister.s3getFirstBatch(KeyLister.java:109)
        at org.cobbzilla.s3s3mirror.KeyLister.<init>(KeyLister.java:37)
        at org.cobbzilla.s3s3mirror.KeyMaster.run(KeyMaster.java:80)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: F9686BB975A72741), S3 Extended Request ID: 80xvNi3MB7XTU7BpjDY7AZ+OY9eJXasWakIS35tnlevhFct6D9m8tLFtLsjmzbY0+GzqsMZMkfQ=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1020)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:675)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:429)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:291)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3655)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3607)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:623)
        at org.cobbzilla.s3s3mirror.KeyLister.s3getFirstBatch(KeyLister.java:96)
        ... 3 more
main INFO : org.cobbzilla.s3s3mirror.MirrorMaster - mirror: completed
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - stopping CopyMaster...
main INFO : org.cobbzilla.s3s3mirror.KeyMaster - CopyMaster stopped
## Thread-1 INFO : org.cobbzilla.s3s3mirror.MirrorStats -

STATS BEGIN
read: 0
copied: 0
copy errors: 0
deleted: 0
delete errors: 0
duration: 0:00:01
read rate: 0.0/minute
copy rate: 0.0/minute
delete rate: 0.0/minute
bytes copied: 0 bytes
GET operations: 5
COPY operations: 0
DELETE operations: 0

**Comment by Observer99** [comment]
I have found a workaround already. 
I have changed the version of aws-java-sdk in pom.xml file to the latest and compiled it:

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>**1.10.75**</version>
        </dependency>

Please confirm that this is a proper solution.

**Comment by Observer99** [comment]
I reached speed about 22 MByte/sec (176 Mbit/sec) while coping large files from bucket in us-east region to a bucket in Frankfurt. The EC2 machine with s3mirror tool is located in us-east.
I used default settings that should give 100 threads. When I increased the amount of threads to 120 I got the following errors:



pool-1-thread-29 INFO : com.amazonaws.http.AmazonHttpClient - Unable to execute HTTP request: Timeout waiting for connection from pool
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
        at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazonaws.http.conn.$Proxy5.getConnection(Unknown Source)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1536)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.keyCopied(KeyCopyJob.java:84)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.run(KeyCopyJob.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
pool-1-thread-95 INFO : com.amazonaws.http.AmazonHttpClient - Unable to execute HTTP request: Timeout waiting for connection from pool
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
        at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazonaws.http.conn.$Proxy5.getConnection(Unknown Source)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1536)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.keyCopied(KeyCopyJob.java:84)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.run(KeyCopyJob.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by cobbzilla** [comment]
Can you try using the `-e` / `--endpoint` option, and see if the warning messages go away? I'm happy to update the AWS dependency, but would like to know that it doesn't slow things down too much.

**Comment by Observer99** [comment]
1. Actually when I tried to copy data inside the same region (from a bucket in us-standard to us- standard), I reached very good speed - 440 MByte/sec (3520 Mbit/sec), so AWS dependency does not slow down the speed.
2. When I placed the EC2 machine in Frankfurt, I reached better speed than when the machine was located in N. Virginia while copying data from us-standard to Frankfurt - 38 Mbyte/sec (304 Mbit/sec).
3. Regarding -e / --endpoint option, my source bucket is located in us-standard and target bucket in Frankfurt, so I don't understand how this should work? If I define a Frankfurt's endpoint, the application will try to access both buckets using only Frankfurt's endpoint? Or there is a possibility to define separate endpoints for source and target buckets?

**Comment by cobbzilla** [comment]
OK, sounds like upgrading the AWS dependency is the right thing to do. The `-e` option indicates the AWS endpoint to send API calls to, but like you I am not sure what is the proper value when doing cross-region copies. But, like you also said, not sure that it matters much. I will keep this issue marked as "bug" until the upgraded dependency is committed (should be soon).

**Comment by Observer99** [comment]
I tried to use "-e s3.eu-central-1.amazonaws.com" option while copying from us-standard to Frankfurt and got the following errors: 

Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - s3getFirstBatch: error listing (try #4): com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3E0CADB7BA581CCD), S3 Extended Request ID: KnEeAs2ITHvx+OkVqHG+YUkkv33RffTxhnX8mjFlcELbajv4L241Dz+7XGUMghUWAfG9NUhDMrU=
Thread-2 ERROR: org.cobbzilla.s3s3mirror.KeyMaster - Unexpected exception in MirrorMaster: java.lang.IllegalStateException: s3getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3E0CADB7BA581CCD), S3 Extended Request ID: KnEeAs2ITHvx+OkVqHG+YUkkv33RffTxhnX8mjFlcELbajv4L241Dz+7XGUMghUWAfG9NUhDMrU=
java.lang.IllegalStateException: s3getFirstBatch: error listing: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3E0CADB7BA581CCD), S3 Extended Request ID: KnEeAs2ITHvx+OkVqHG+YUkkv33RffTxhnX8mjFlcELbajv4L241Dz+7XGUMghUWAfG9NUhDMrU=
        at org.cobbzilla.s3s3mirror.KeyLister.s3getFirstBatch(KeyLister.java:109)
        at org.cobbzilla.s3s3mirror.KeyLister.<init>(KeyLister.java:37)
        at org.cobbzilla.s3s3mirror.KeyMaster.run(KeyMaster.java:80)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3E0CADB7BA581CCD), S3 Extended Request ID: KnEeAs2ITHvx+OkVqHG+YUkkv33RffTxhnX8mjFlcELbajv4L241Dz+7XGUMghUWAfG9NUhDMrU=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3778)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:610)
        at org.cobbzilla.s3s3mirror.KeyLister.s3getFirstBatch(KeyLister.java:96)
        ... 3 more

**Comment by Observer99** [comment]
In addition, as I have mentioned before, if I set number of threads more then 100 (for example -t 150 option), I get error messages, yet s3s3mirror is still working and successfully finishes the task.



pool-1-thread-42 INFO : com.amazonaws.http.AmazonHttpClient - Unable to execute HTTP request: Timeout waiting for connection from pool
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
        at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazonaws.http.conn.$Proxy5.getConnection(Unknown Source)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1536)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.keyCopied(KeyCopyJob.java:84)
        at org.cobbzilla.s3s3mirror.KeyCopyJob.run(KeyCopyJob.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by cobbzilla** [comment]
Seems like the right thing to do would be (1) notice the 301 (2) stop using that endpoint, and use the one specified in the Location header of the 301 response. @Observer99 - would you agree?

**Comment by Observer99** [comment]
I think the right thing would be possibility to specify appropriate endpoint in each region for both buckets, but I'm not sure if it's possible. But using an endpoint specified in the Location header of the 301 response would be a good workaround.
